version: '3.8'

services:
  
  db:
    image: mysql:8.1
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wppassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
    - "db"
    ports:
    - "8080:80"
    depends_on:
    - db

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    links:
      - "db"